### PR TITLE
Update csv_search_tool.py with support to use MultiCSV Search

### PR DESCRIPTION
**Pull request by amjadraza**
Extended the original feature of `CSVSearchTool` to `MultiCSVSearchTool`. 

Use: 

```
from crewai_tools import CSVSearchTool

# Initialize the tool with a specific CSV file. This setup allows the agent to search over given CSV files.
multi_csv_tool = CSVSearchTool(csv_list=['path/to/your/csvfile1.csv', 'path/to/your/csvfile2.csv'] )

```

### CODE REVIEW

**Comment by gvieira** [comment]
Hey @amjadraza! Thanks for the PR! It does make sense and we understand the use case.

I'm about to push a PR that's going to allow follow up `add`s to any rag tool, like so:

```python
tool = CSVSearchTool()
tool.add("path/to/your/csvfile1.csv")
tool.add("path/to/your/csvfile2.csv")
```

Do you think it would be useful for you?

**Comment by amjadraza** [comment]
> Hey @amjadraza! Thanks for the PR! It does make sense and we understand the use case.
> 
> I'm about to push a PR that's going to allow follow up `add`s to any rag tool, like so:
> 
> ```python
> tool = CSVSearchTool()
> tool.add("path/to/your/csvfile1.csv")
> tool.add("path/to/your/csvfile2.csv")
> ```
> 
> Do you think it would be useful for you?

Yes, it will have many use cases. I am using one right now. 

Moreover, the RAG system may have a tool that can Ingest, any type of file format. e.g. csv, pdf, youtube, HTML, and txt. This is very well possible with embedchain anyway. 

Would love to help if needed.  Thanks

**Comment by gvieira** [comment]
Great to know, @amjadraza! The PR is live here https://github.com/joaomdmoura/crewAI-tools/pull/16, if you are curious.

Also, you could potentially use the generic `RagTool`. When my PR goes live you'll be able to simply call the `add` method like you would normally do for embedchain.

**Comment by joaomdmoura** [comment]
@gvieira given your changes we probably don't want to merge this any longer?

**Comment by gvieira** [comment]
@joaomdmoura Yeah, I think this is now not needed anymore. Still, we appreciate the suggestion. Closing it.

**Pull request closed without merging**
