### PR TITLE
added Firecrawl tools

### PR DESCRIPTION
**Pull request by rafaelsideguide**
This PR introduces [Firecrawl](https://www.firecrawl.dev/) tools, enabling the following features:
- Scrape (with LLM Extraction)
- Crawl
- Search

@joaomdmoura, hope you don't mind me just doing a PR, haha! Thank you for creating this amazing tool!

### CODE REVIEW

**Comment by nickscamara** [comment]
Hey @joaomdmoura. We have so many requests for having Firecrawl in crew. Would be awesome to collab. lmk if you need any help or anything! 

Valeu! tmj!

**Comment by cirrus3d** [comment]
Since we are waiting for a merge and in order to test this pull request in my local MacOS environment I did the following:

- Uninstalled crewai_tools pip package
- Did a `pip install --user git+https://github.com/joaomdmoura/crewAI-tools.git@41e3d6b7b32258c2c31dbae45fc12e2bdcbd786b`
- In /Users/{myuser}/.local/lib/python3.11/site-packages/crewai_tools/tools/__init__.py I added the line: `from .firecrawl_crawl_website_tool.firecrawl_crawl_website_tool import FirecrawlCrawlWebsiteTool`
- In /Users/{myuser}/.local/lib/python3.11/site-packages/crewai_tools/__init__.py I added the line: `FirecrawlCrawlWebsiteTool,`

**Comment by cirrus3d** [comment]
Hi @joaomdmoura,

How would I run your example with a local Firecrawl server installed in port 3002? It seems that I get an error that token is invalid (or missing if I do not specify it).

**Comment by nickscamara** [comment]
Hey @joaomdmoura any chance we can get this in? We are getting tons of requests. Let me know if you need any help! Valeu :)

**Comment by joaomdmoura** [comment]
@nickscamara merged will be live in thenew version, I'll try cutting it this week

**Comment by nickscamara** [comment]
Let's goo! 🔥  Thanks @joaomdmoura!

**Pull request merged**
